default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  host: localhost
  port: 5432
  username: postgres
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
